#!/bin/bash

function abort {
    echo $1
    exit 1
}

# disallow commits if a test uses 'fit'.
rootDir=$(git rev-parse --show-toplevel)
if grep -q -r --include="*.js" "fit(\|fit_exclude_dbs(" ${rootDir}/spec
then
    # found
    abort "pre-commit: Aborting commit because a test uses 'fit'."
fi
